[package]
name = "rtfg-core"
version = "0.1.0"
edition = "2024"



[dependencies]
cgroups = "0.1.0"
ebpf = { path = "../ebpf"}
log = "0.4.27"
procfs = "0.17.0"
serde = { version = "1.0.219", features = ["derive"] }
sysinfo = "0.34.2"
thiserror = "2.0.12"


